apiVersion: v1
kind: Service
metadata:
  name: minio-sc
  namespace: minio
  labels:
    app: minio
spec:
  ports:
  - port: 9000
    name: web
  selector:
    app: minio
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: minio
  name: minio
spec:
  selector:
    matchLabels:
      app: minio
  serviceName: minio-sc
  replicas: 1
  template:
    metadata:
      labels:
        app: minio
    spec:
      containers:
      - args:
        - server
        - /data
        image: minio/minio
        name: minio
        env:
        - name: MINIO_ROOT_USER
          valueFrom:
            secretKeyRef:
              name: minio-secret
              key: MINIO_ROOT_USER
        - name: MINIO_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: minio-secret
              key: MINIO_ROOT_PASSWORD
        ports:
        - containerPort: 9000
          name: minio
        volumeMounts:
        - name: minio-pvc
          mountPath: /data
  volumeClaimTemplates:
  - metadata:
      name: minio-pvc
    spec:
      storageClassName: manual
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 5Gi
